name: flutter_hemanth_dev
description: A portfolio website for Hemanth S.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  go_router: ^4.1.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  material_design_icons_flutter: ^5.0.6295
  provider: ^6.0.1
  responsive_builder: ^0.4.1
  url_launcher: ^6.0.12
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "Portfolio - Hemanth S"

flutter_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
